name: Android CI - Build AAR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    # add chmod to gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build AAR for spinview module
    - name: Build AAR
      run: ./gradlew :easyprefs:assembleRelease

    # Archive AAR
    - name: Upload AAR
      uses: actions/upload-artifact@v3
      with:
        name: easyprefs-release-aar
        path: easyprefs/build/outputs/aar/*.aar
